# Generated by Django 5.0.6 on 2024-07-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resizing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresizing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
