# Generated by Django 4.2.8 on 2024-07-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecreatedBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_option', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.background')),
            ],
        ),
    ]
