# Generated by Django 5.0.7 on 2024-07-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recreated_background', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recreatedbackground',
            name='concept_option',
        ),
    ]
