# Generated by Django 5.0.7 on 2024-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreated_background', '0002_remove_recreatedbackground_concept_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreatedbackground',
            name='concept_option',
            field=models.TextField(default='default_concept'),
        ),
    ]
