# Generated by Django 5.0.6 on 2024-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ad_text2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='serve_text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
